// <auto-generated />
using F1Fantasy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace F1Fantasy.Migrations
{
    [DbContext(typeof(F1FantasyDbContext))]
    [Migration("20260220155833_AddPitStopsTable")]
    partial class AddPitStopsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("F1Fantasy.Models.Circuit", b =>
                {
                    b.Property<string>("CircuitId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CircuitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("CircuitId");

                    b.ToTable("Circuits");
                });

            modelBuilder.Entity("F1Fantasy.Models.Constructor", b =>
                {
                    b.Property<string>("ConstructorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ConstructorId");

                    b.ToTable("Constructors");
                });

            modelBuilder.Entity("F1Fantasy.Models.Driver", b =>
                {
                    b.Property<string>("DriverId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("F1Fantasy.Models.PitStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Lap")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Stop")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("Season", "Round");

                    b.HasIndex("Season", "Round", "DriverId");

                    b.ToTable("PitStops");
                });

            modelBuilder.Entity("F1Fantasy.Models.Qualifying", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConstructorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Q1")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Q2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Q3")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("DriverId");

                    b.HasIndex("Season", "Round");

                    b.ToTable("Qualifyings");
                });

            modelBuilder.Entity("F1Fantasy.Models.Race", b =>
                {
                    b.Property<string>("Season")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Round")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Season", "Round");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("F1Fantasy.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConstructorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Grid")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsSprint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Laps")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Points")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PositionText")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("DriverId");

                    b.HasIndex("Season", "Round");

                    b.HasIndex("Season", "Round", "IsSprint");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("F1Fantasy.Models.Season", b =>
                {
                    b.Property<string>("Year")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Year");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("F1Fantasy.Models.Circuit", b =>
                {
                    b.OwnsOne("F1Fantasy.Models.Location", "Location", b1 =>
                        {
                            b1.Property<string>("CircuitId")
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Lat")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Locality")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Long")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("CircuitId");

                            b1.ToTable("Circuits");

                            b1.WithOwner()
                                .HasForeignKey("CircuitId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("F1Fantasy.Models.Race", b =>
                {
                    b.OwnsOne("F1Fantasy.Models.Session", "FirstPractice", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.OwnsOne("F1Fantasy.Models.Session", "Qualifying", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.OwnsOne("F1Fantasy.Models.Session", "SecondPractice", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.OwnsOne("F1Fantasy.Models.Session", "Sprint", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.OwnsOne("F1Fantasy.Models.Session", "SprintQualifying", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.OwnsOne("F1Fantasy.Models.Session", "ThirdPractice", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.Navigation("FirstPractice");

                    b.Navigation("Qualifying");

                    b.Navigation("SecondPractice");

                    b.Navigation("Sprint");

                    b.Navigation("SprintQualifying");

                    b.Navigation("ThirdPractice");
                });

            modelBuilder.Entity("F1Fantasy.Models.Result", b =>
                {
                    b.OwnsOne("F1Fantasy.Models.FastestLap", "FastestLap", b1 =>
                        {
                            b1.Property<int>("ResultId")
                                .HasColumnType("integer");

                            b1.Property<string>("Lap")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Rank")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.HasKey("ResultId");

                            b1.ToTable("Results");

                            b1.WithOwner()
                                .HasForeignKey("ResultId");

                            b1.OwnsOne("F1Fantasy.Models.AverageSpeed", "AverageSpeed", b2 =>
                                {
                                    b2.Property<int>("FastestLapResultId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Speed")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)");

                                    b2.Property<string>("Units")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)");

                                    b2.HasKey("FastestLapResultId");

                                    b2.ToTable("Results");

                                    b2.WithOwner()
                                        .HasForeignKey("FastestLapResultId");
                                });

                            b1.OwnsOne("F1Fantasy.Models.LapTime", "Time", b2 =>
                                {
                                    b2.Property<int>("FastestLapResultId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Time")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.HasKey("FastestLapResultId");

                                    b2.ToTable("Results");

                                    b2.WithOwner()
                                        .HasForeignKey("FastestLapResultId");
                                });

                            b1.Navigation("AverageSpeed");

                            b1.Navigation("Time")
                                .IsRequired();
                        });

                    b.OwnsOne("F1Fantasy.Models.ResultTime", "Time", b1 =>
                        {
                            b1.Property<int>("ResultId")
                                .HasColumnType("integer");

                            b1.Property<string>("Millis")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("ResultId");

                            b1.ToTable("Results");

                            b1.WithOwner()
                                .HasForeignKey("ResultId");
                        });

                    b.Navigation("FastestLap");

                    b.Navigation("Time");
                });
#pragma warning restore 612, 618
        }
    }
}
