// <auto-generated />
using F1Fantasy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace F1Fantasy.Migrations
{
    [DbContext(typeof(F1FantasyDbContext))]
    partial class F1FantasyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("F1Fantasy.Models.Circuit", b =>
                {
                    b.Property<string>("CircuitId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CircuitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("CircuitId");

                    b.ToTable("Circuits");
                });

            modelBuilder.Entity("F1Fantasy.Models.Constructor", b =>
                {
                    b.Property<string>("ConstructorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ConstructorId");

                    b.ToTable("Constructors");
                });

            modelBuilder.Entity("F1Fantasy.Models.Driver", b =>
                {
                    b.Property<string>("DriverId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("F1Fantasy.Models.Race", b =>
                {
                    b.Property<string>("Season")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Round")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Season", "Round");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("F1Fantasy.Models.Season", b =>
                {
                    b.Property<string>("Year")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Year");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("F1Fantasy.Models.Circuit", b =>
                {
                    b.OwnsOne("F1Fantasy.Models.Location", "Location", b1 =>
                        {
                            b1.Property<string>("CircuitId")
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Lat")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Locality")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Long")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("CircuitId");

                            b1.ToTable("Circuits");

                            b1.WithOwner()
                                .HasForeignKey("CircuitId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("F1Fantasy.Models.Race", b =>
                {
                    b.OwnsOne("F1Fantasy.Models.Session", "FirstPractice", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.OwnsOne("F1Fantasy.Models.Session", "Qualifying", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.OwnsOne("F1Fantasy.Models.Session", "SecondPractice", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.OwnsOne("F1Fantasy.Models.Session", "Sprint", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.OwnsOne("F1Fantasy.Models.Session", "SprintQualifying", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.OwnsOne("F1Fantasy.Models.Session", "ThirdPractice", b1 =>
                        {
                            b1.Property<string>("RaceSeason")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("RaceRound")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("RaceSeason", "RaceRound");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceSeason", "RaceRound");
                        });

                    b.Navigation("FirstPractice");

                    b.Navigation("Qualifying");

                    b.Navigation("SecondPractice");

                    b.Navigation("Sprint");

                    b.Navigation("SprintQualifying");

                    b.Navigation("ThirdPractice");
                });
#pragma warning restore 612, 618
        }
    }
}
